src/Cabal2Nix/Flags.hs

This is required to create the diagrams-builder package without manually changing its nix expression.

Diagrams-builder enabling of flags for all supported backends.

---

src/hackage2nix.hs

0.0.7 is broken anyway, and newer versions can build against 7.10 at least

Remove amazonka overrides

---

src/hackage2nix.hs

I tried updating elm instead but it's not entirely trivial so this is
a quick fix until elm has been updated by its maintainers.

Add special case for optparse-applicative 0.10.

---

src/Cabal2Nix/Package.hs

Failing silently in case of an IO error is really confusing. This patch makes cabal2nix at least print a message.

Better error reporting in case of IO errors

---

src/Cabal2Nix/PostProcess.hs

liquid-fixpoint needs the `-fbuild-external` flag to force building the
ocaml binary locally instead of using a precompiled binary (not
guaranteed to work in nixos AFAIK)

update post-processing for liquid-fixpoint and liquidhaskell

---

src/hackage2nix.hs

When constraint on `haddock-library` version is lifted, we'll need to add it there too and override it for GHC 7.8.

hackage2nix.hs: add old haddock-api for GHC 7.8

---

src/hackage2nix.hs

Both builds work now on GHC 7.10.
data-hash was fixed in https://github.com/NixOS/nixpkgs/pull/7693
uhc-light has been fixed upstream

Enable fixed data-hash, uhc-light builds

---

src/Cabal2Nix/PostProcess.hs

NB: `z3` takes a while to build (and liquidhaskell has a large testsuite too). Should we mention this somewhere so people can be aware and possibly choose to disable tests locally?

add `z3` to the buildTools for liquid-fixpoint and liquidhaskell so we can run the tests

---

src/hackage2nix.hs

http://hydra.cryp.to/build/864879/log/raw - this error was fixed in the last version of `meep` package.
Can we remove it now from the list of broken packages?

hackage2nix: whitelist meep package

---

src/hackage2nix.hs

Agda since had a release and we no longer use those

don't specify ccphs/equivalence versions

---

src/Cabal2Nix/PostProcess.hs

It fails to build with
```
Executing: dist/build/Z3/Base/C_hsc_make  >dist/build/Z3/Base/C.hs
dyld: Library not loaded: libz3.dylib
Referenced from: dist/build/Z3/Base/C_hsc_make
Reason: image not found
running dist/build/Z3/Base/C_hsc_make failed (exit code -5)
command was: dist/build/Z3/Base/C_hsc_make  >dist/build/Z3/Base/C.hs
```
otherwise.

Add z3 to the DYLD_LIBRARY_PATH on darwin

---

src/Cabal2Nix/PostProcess.hs
src/hackage2nix.hs

The building of the `gf` Haskell package is a bit special. Not only it builds the `gf` compiler and related Haskell libraries, but also a standard library for the GF (Grammatical Framework) programming language, which are themselves compiled with the `gf` compiler. 
This change allows for the full `gf` package to be built.

Fix build for haskell package 'gf'

---

src/hackage2nix.hs

adding the lmdb c library to nixpkgs seems to fix breakage:
nixos/nixpkgs@9d85874aeb6f17bc1b13c1a248f319e1908e1210
This also unbreaks vache and vcache-trie which are currently
marked broken in nixpkgs

lmdb: remove from broken packages

---

src/Cabal2Nix/Package.hs

Currently, when running `cabal2nix . > foo.nix` against a malformed cabal file, the error message ends up in `foo.nix` and `cabal2nix` appears to fail silently, which is not ideal.

Write error messages for parse failures to stderr

---

src/Cabal2Nix/Package.hs
src/Distribution/Nixpkgs/Fetch.hs
src/cabal2nix.hs
src/hackage2nix.hs

This fixes #140.
Before:
```
+ rm -rf /home/jchee/.cache/cabal2nix
+ .cabal-sandbox/bin/cabal2nix --sha256 foo cabal2nix.cabal
+ grep sha256
sha256 = "foo";
+ cat /home/jchee/.cache/cabal2nix/cabal2nix-20150716.sha256 /dev/fd/63
++ echo
foo
+ .cabal-sandbox/bin/cabal2nix cabal://cabal2nix
mirror://hackage/cabal2nix-1.73.tar.gz expands to http://hackage.haskell.org/package/cabal2nix-1.73.tar.gz
% Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
Dload  Upload   Total   Spent    Left  Speed
0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100 27048  100 27048    0     0  80933      0 --:--:-- --:--:-- --:--:-- 80933
path is ‘/nix/store/wvwx9jxca3fbvrd95kknzsp3hy2jma4d-cabal2nix-1.73.tar.gz’
{ mkDerivation, base, Cabal, containers, …
```

Don't store hashes taken from the command line.

---

src/Cabal2Nix/Normalize.hs
src/hackage2nix.hs

System packages which have the same package name as haskell packages should be brought
into scope by using `inherit systemPackageName;`. Previously, `hackage2nix` would
generate `systemPackageName = null` or nothing at all instead.
The change introduces a slight problem for executables that depend on themselves as a
tool (c2hs' testsuite for example depends on the c2hs tool). To fix this, such a
dependency is now removed in the normalization step of cabal2nix.

Fix package lookup for shadowed system packages

---

distribution-nixpkgs/src/Distribution/Nixpkgs/Haskell/FromCabal/PostProcess.hs

It requires some environment variables to be set in order to run against
a Twilio account. Not something we want to do I don't think.

twilio: disable test suite

---

distribution-nixpkgs/src/Distribution/Nixpkgs/Haskell/FromCabal/PostProcess.hs

This package has been broken since haskellPackages.git was introduced a
couple of weeks ago *and* the newer version became the default, because
only this specific rev was getting the pkg.git dependency.  Simply
loosen the dependency to fix.

hlibgit2: all newer versions should get pkg.git

---

distribution-nixpkgs/src/Distribution/Nixpkgs/Haskell/FromCabal/PostProcess.hs

See the [nixpkgs pull request](https://github.com/NixOS/nixpkgs/pull/15696). This replaces its first commit only. It seems to do the right thing on `./result/bin/cabal2nix cabal://Agda` and `./result/bin/cabal2nix cabal://Agda-2.4.2.4`.

Agda: new postInstall for version 2.5, which has new builtin modules

---

distribution-nixpkgs/distribution-nixpkgs.cabal
distribution-nixpkgs/package.yaml
distribution-nixpkgs/src/Distribution/Nixpkgs/Fetch.hs
distribution-nixpkgs/src/Distribution/Nixpkgs/Haskell/BuildInfo.hs
distribution-nixpkgs/src/Distribution/Nixpkgs/Haskell/Derivation.hs
distribution-nixpkgs/src/Distribution/Nixpkgs/Haskell/FromCabal/Configuration.hs
distribution-nixpkgs/src/Distribution/Nixpkgs/Haskell/OrphanInstances.hs
distribution-nixpkgs/src/Distribution/Nixpkgs/License.hs
distribution-nixpkgs/src/Distribution/Nixpkgs/Meta.hs
hackage2nix/hackage2nix.cabal
hackage2nix/package.yaml
hackage2nix/src/Stackage.hs

As of deepseq-1.4.0, the ability to derive generics has been folded into the main library.  Furthermore, deepseq-1.4.2.0 is included with ghc-8.0.1 (and 1.4.1.1 was bundled with ghc-7.10.1).
Before this change, attempts to compile with ghc-8.0.1 would throw errors like:
```
src/Distribution/Nixpkgs/Haskell/OrphanInstances.hs:32:10: error:
Not in scope: type constructor or class ‘NFData’
```
Changing to just use the automatic deriviation seemed like the easiest way to resolve the issue.  I *believe* this will just work on 7.10.x and with the exception of  a couple of terms, might simply work all the way back to the "beginning of time"...or at least when NFData first appeared.

Allow building with ghc-8.0.1

---

cabal2nix/src/Main.hs

This is useful for specifying the branch in "if impl(...)" expressions.
Useful for generating nix expression for projects that support both GHC
and GHCJS, but have different dependencies depending on the compiler.

Add flag (--impl) for specifying compiler id.

---

src/Distribution/Nixpkgs/Haskell/FromCabal/PostProcess.hs

`gi-javascriptcore` fails to build due to:
```
Did not find a GI repository for JavaScriptCore-3.0 in
["/usr/local/share/gir-1.0","/usr/share/gir-1.0"]
```
This is related to https://github.com/haskell-gi/haskell-gi/issues/36, so I copied what was done for other gi-* packages.
I haven't tested this patch locally so please review it carefully.

Override GIR search path for gi-javascriptcore

---

src/Distribution/Nixpkgs/Haskell/FromCabal/PostProcess.hs

qtah-cpp-qt5 and qtah-qt5 need Qt supplied as a build input.  Both invoke qmake (provided by `qt5.qtbase`) during the configure phase, and qtah-cpp-qt5 also links to Qt libraries.
I hit dependency issues trying to build cabal2nix locally to test this PR, but I'm trying to create this change in Nixpkgs: https://github.com/khumba/nixpkgs/commit/206292273500a51fbf19cc93f17c292df8d1ad34, and Qtah builds successfully at that commit.

Supply Qt 5 to Qtah.

---

src/Distribution/Nixpkgs/Haskell/FromCabal/Name.hs

Used by the pulseaudio package

Add name mapping for pulse

---

src/Distribution/Nixpkgs/Haskell/FromCabal/PostProcess.hs

This gets the correct versions of the libraries into scope.  It is not a complete fix for the build.

Use gstreamer-1.X for building gi-gst*

---

src/Distribution/Nixpkgs/Haskell/FromCabal/PostProcess.hs

Fixes https://github.com/NixOS/nixpkgs/issues/18795.
/cc @mulderr

gi-pango: the setup script depends on libcairo-gobjects at run-time

---

src/Distribution/Nixpkgs/Haskell/Hackage.hs
src/Distribution/Nixpkgs/Haskell/PackageSourceSpec.hs

@peti This fixes the issue I mentioned, #255.

Enabled cabal2nix to hash the Cabal file when --hackage-db is specified.

---

src/Distribution/Nixpkgs/Haskell/FromCabal/PostProcess.hs

Add overrides to let gi-pangocairo build. Relevant to NixOS/nixpkgs#21993.
I have tested this with:
```
./dist/build/cabal2nix/cabal2nix --shell cabal://gi-pangocairo > gi-pangocairo.nix
nix-build gi-pangocairo.nix
```
In the cabal2nix case, the `system-pango = pkgs.pango` and `system-cairo = pkgs.cairo` variables need to be manually added to the `callPackage ` arguments. But I am assuming that with hackage2nix, it will just work, as it does for the `gio` package (`system-gio = pkgs.gio`).

Add post-processing for gi-pangocairo

---

src/Distribution/Nixpkgs/Haskell/FromCabal/License.hs

```
cabal2nix: Distribution.Nixpkgs.Haskell.FromCabal.License.fromCabalLicense: unknown licenseUnknownLicense "GPL3"
Choose one of: GPL, GPL-2, GPL-3, LGPL, LGPL-2.1, LGPL-3, AGPL, AGPL-3, BSD2, BSD3, MIT, ISC, MPL-2.0, Apache, Apache-2.0, PublicDomain, AllRightsReserved, OtherLicense
CallStack (from HasCallStack):
error, called at src/Distribution/Nixpkgs/Haskell/FromCabal/License.hs:36:59 in cabal2nix-2.1.1-Ha1HfKuK3utC69EpNllx2j:Distribution.Nixpkgs.Haskell.FromCabal.License
```

improve license error

---

src/Distribution/Nixpkgs/Haskell/FromCabal/Name.hs

In b7ccf27229d9479e5cea2f2d2c2b06477d9e3049, Volth
<volth@webmaster.ms> renamed several webkitgtk packages.
Unfortunately, the changes to the haskell package file were not
reflected here, which means they would go away on the next
regeneration.

Fixup webkitgtk package names

---

src/Distribution/Nixpkgs/Haskell/FromCabal.hs

I would like to expose the intermediate finalization step of `fromGenericPackageDescription` as an extra `finalizeGenericPackageDescription` function. This would help my pet stackage2nix project.
Just a refactoring, the logic stays same.

Expose Cabal finalization function

---

src/Distribution/Nixpkgs/Haskell/FromCabal/PostProcess.hs

Relevant nixpkgs issues - https://github.com/NixOS/nixpkgs/issues/28466 & https://github.com/NixOS/nixpkgs/issues/28643
Agda itself builds but can't build other packages:
- https://hydra.nixos.org/build/59622963
- https://hydra.nixos.org/build/59621250
I only tested Agda >= 2.5 case by building `nixpkgs.agdaPrelude` and `nixpkgs.AgdaStdlib` against a recent nixpkgs master and Agda expression adjusted as per output of cabal2nix with this change. I'm assuming the same issue exists for Agda < 2.5.

Agda: fix postInstall to account for multiple outputs.

---

src/Distribution/Nixpkgs/Haskell/FromCabal/Name.hs

Set the mapping for the cabal "ssh2" package to the Nix "libssh2" package.

Mapping for libssh2

---

src/Distribution/Nixpkgs/Haskell/FromCabal/Flags.hs

If you don't pass this flag then the package fails to build due to linker
errors.
In nixpkgs this flag is currently passed manually. The libraries are
built later on. 
https://github.com/NixOS/nixpkgs/blob/1c431f4664d219368710c2db1d1b81e6e556978f/pkgs/development/haskell-modules/configuration-common.nix#L737

Add -fexeconly flag to idris package

---

src/Cabal2nix.hs
src/Distribution/Nixpkgs/Haskell/PackageSourceSpec.hs

Added hackage snapshot time as an argument.
Local tests:
```
./dist/build/cabal2nix/cabal2nix --hackage-snapshot="09.08.2017 10:54 AM" cabal://mtl
{ mkDerivation, base, stdenv, transformers }:
mkDerivation {
pname = "mtl";
version = "2.2.1";
sha256 = "cae59d79f3a16f8e9f3c9adc1010c7c6cdddc73e8a97ff4305f6439d855c8dc5";
revision = "1";
editedCabalFile = "0fsa965g9h23mlfjzghmmhcb9dmaq8zpm374gby6iwgdx47q0njb";
libraryHaskellDepends = [ base transformers ];
homepage = "http://github.com/ekmett/mtl";
description = "Monad classes, using functional dependencies";
license = stdenv.lib.licenses.bsd3;
}
```
```
./dist/build/cabal2nix/cabal2nix --hackage-snapshot="09.08.2011 10:54 AM" cabal://mtl
{ mkDerivation, base, stdenv, transformers }:
mkDerivation {
pname = "mtl";
version = "2.0.1.0";
sha256 = …
```

Added hackage snapshot time as an argument to cabal2nix.

---

src/Cabal2nix.hs
src/Distribution/Nixpkgs/Haskell/PackageSourceSpec.hs

As noted in #313, HackageDB deserialization is rather expensive. This
change allows Haskell projects to deserialize a HackageDB once, and
then make multiple calls to cabal2nix with that DB.
An experimental result with stack2nix shows over a 6x speed
improvement with pandoc and its dependency closure.

Optimization: allow HackageDB reuse

---

src/Distribution/Nixpkgs/Haskell/FromCabal.hs

- Filter the dependency set using the subLibraries names
- Add the subLibraries deps to the derivation deps
I **think** the second is also required to provide the right dependencies for `nix-shell`.

Support for Cabal 2.x internal library (issue #315)

---

src/Cabal2nix.hs
src/Distribution/Nixpkgs/Haskell/PackageSourceSpec.hs

I don't like this solution too much, but it does the job. 
Fixes #319

Make HackageDB lazy to avoid unnecessary parsing

---

src/Distribution/Nixpkgs/Haskell/FromCabal/PostProcess.hs

Fixes NixOS/nixpkgs#33363.
I'm not yet able to run hackage2nix to check this change (wrong cabal version), but pretty sure it will work.

X11: add libXScrnSaver to system library depends

---

src/Distribution/Nixpkgs/Haskell/FromCabal/Name.hs

i tested this with my branch of `fltkhs` (which declares system dependencies in the cabal file), and the default `cabal2nix` works correctly. this fixes `haskellPackages.fltkhs` (currently marked broken). 
this pull request, along with https://github.com/deech/fltkhs/pull/71 , fixes https://github.com/deech/fltkhs/issues/16

fltk-config build tool from fltk, for fltkhs

---

cabal2nix.cabal
src/Distribution/Nixpkgs/Haskell/PackageSourceSpec.hs

This should probably wait for a reply from the hpack author for clarification of the extra filepath argument, but I think it can be ignored. This commit works for hpack-0.21 and hpack-0.22.
Can remove the macros if you'd rather just drop support for <0.22.

Fix build for hpack-0.22.0.

---

src/Distribution/Nixpkgs/Haskell/Derivation.hs

The remnants of https://github.com/NixOS/cabal2nix/pull/335

base-4.11/GHC 8.4 compat:  SMP conflict between 'base' and 'pretty'

---

src/Cabal2nix.hs

That way we can use `cabal2nix` when cross compiling to windows as well.

Add `Windows` to platforms.

---

src/Cabal2nix.hs

This adds support for all of the architectures listed in `nixpkgs/lib/systems/platforms.nix`.

Add support for more Cabal platforms

---

src/Distribution/Nixpkgs/Haskell/FromCabal/Name.hs

This is necessary to get the gi-gdkx11 package compiling.

gdk-x11-3.0: point to the gtk3 package

---

src/Distribution/Nixpkgs/Haskell/PackageSourceSpec.hs

Note I haven't built this because I could find neither instructions against which nixpkgs I should best build this nor a `stack.yaml` so I'll just leave it here relying on your goodwill to typecheck it for me @peti :-)

fetchOrFromDB: Show which source failed when calling `fail`

---

hackage2nix/Main.hs

The hackage page is always there, and supports a TLS connection.

hackage2nix: clear homepage

---

src/Cabal2nix.hs
src/Distribution/Nixpkgs/Haskell/Hackage.hs

1) Changes previous:
```haskell
cabal2nix' :: [String] -> IO (Either Doc Derivation)
cabal2nixWithDB :: DB.HackageDB -> [String] -> IO (Either Doc Derivation)
```
into more typed
```haskell
cabal2nix' :: Options -> IO (Either Doc Derivation)
cabal2nixWithDB :: DB.HackageDB -> Options -> IO (Either Doc Derivation)
parseArgs :: [String] -> IO Options
```
2) Allows setting nixpkgs identifier with `Options`
3) Exposes a function to ease use of Distribution.Nixpkgs.Haskell.Hackage module
These changes are required to make next release of https://github.com/input-output-hk/stack2nix

Refactor cabal2nix lib api

---

src/Distribution/Nixpkgs/Haskell/FromCabal/PostProcess.hs
test/golden-test-cases/nvim-hs.nix.golden
test/golden-test-cases/pinch.nix.golden
test/golden-test-cases/test-fixture.nix.golden

See comment in code for more details.
The cross change is unambiguously a good thing, and put in the first commit. The `*-discover` hack is more a stop-gap until packages stop being broken---we're *not* hacking around a Nix deficiency with `strictDeps` here. It relies on the cross change because rather than changing what sort of dependency `*-discover` is, it adds a new dependency in case it was actually wanted as a library, which would be removed.
Fixes #356
CC @matthewbauer @domenkozar

Add hack for common erroneous missing build-tool-depends, and keep duplicate deps for cross

---

src/Distribution/Nixpkgs/Haskell/FromCabal/PostProcess.hs

@peti I'm [working](https://github.com/NixOS/nixpkgs/pull/43867) to get `haskell.packages.ghc822.tensorflow` to build. The following is required for that.

Add protobuf dependency to packages that need the protoc compiler

---

src/Distribution/Nixpkgs/Haskell/FromCabal/Name.hs

This patch produces the following correct derivation. This now works because nixpkgs recently [gained the `libtensorflow` attribute](https://github.com/NixOS/nixpkgs/commit/1c48e89eb138c75ca8ebf95a6aa13078c03be9d5#diff-036410e9211b4336186fc613f7200b12R863).
```
$ dist/build/cabal2nix/cabal2nix cabal://tensorflow
{ mkDerivation, async, attoparsec, base, bytestring, c2hs
, containers, data-default, exceptions, fgl, HUnit, lens-family
, libtensorflow, mainland-pretty, mtl, proto-lens
, proto-lens-protoc, semigroups, split, stdenv, temporary
, tensorflow-proto, test-framework, test-framework-hunit
, test-framework-quickcheck2, text, transformers, vector
}:
mkDerivation {
pname = "tensorflow";
version = "0.1.0.2";
sha256 = "13b08d98cea0bde47b2e2ed9bc51937add0708eb50ef06e504100a447be92d50"; …
```

libNixName: map tensorflow to libtensorflow

---

hackage2nix/Main.hs

Hi all,
This tiny patch just updates an error message to highlight the line in the [README](https://github.com/NixOS/cabal2nix/blob/master/hackage2nix/README.md) about using a case-sensitive file system.
I got this error while trying to use hackage2nix:
```
hackage2nix: constraint cassava ==0.5.1.0 cannot be resolved in Hackage
```
and like a fool I tried other things before realising I had skipped that part 😄 
Thanks!

Update error message for unresolved constraints

---

src/Cabal2nix.hs
src/Distribution/Nixpkgs/Fetch.hs
src/Distribution/Nixpkgs/Haskell/PackageSourceSpec.hs

There are times when submodule fetching is unnecessary (e.g. the submodules will be built as separate nix packages), so it would be nice to suppress this for git repos with extensive or recursive submodules.  This patch leaves the default behavior to fetch the submodules, but adds an option to disable that.
$ diff <(time cabal2nix https://github.com/GaloisInc/macaw-semmc --subpath macaw-semmc 2> /dev/null) \
<(time cabal2nix https://github.com/GaloisInc/macaw-semmc --subpath macaw-semmc --no-submodules 2> /dev/null)
real    0m2.169s
user    0m0.105s
sys     0m0.037s
real    1m16.636s
user    0m6.695s
sys     0m1.449s
11c11
<     sha256 = "16gmdhxn92qxpqlx2p2bd4cg1zpjsv5qa8hf4riymsifndrfcnvx";
---
>     sha256 = "0yc5y9vcvkri2cj5mma37jca07srlm8h089pqrq9zh9g63aa1b9w";
$

Add --no-submodules option to suppress fetching submodules (e.g. git).

---

hackage2nix/Main.hs
src/Distribution/Nixpkgs/Fetch.hs
src/Distribution/Nixpkgs/Haskell/Derivation.hs
src/Distribution/Nixpkgs/Haskell/PackageSourceSpec.hs
test/Main.hs

This was overlooked in my previous (accepted) patch which adds the `--dont-fetch-submodules` command-line flag: the generated nix specification for `src` should reflect the setting of that flag so that the corresponding `fetchgit` operation behaves similarly.  This has no effect for `src` directives that do not use `fetchgit`.

Output fetchSubmodules setting in src directive

---

src/Distribution/Nixpkgs/Haskell/FromCabal.hs
src/Distribution/Nixpkgs/Haskell/FromCabal/License.hs

Cabal supports SPDX license expressions, which support a wider range of licenses
than the original Cabal license syntax.

Translate SPDX license expressions

---

src/Distribution/Nixpkgs/Haskell/PackageSourceSpec.hs

hpack infers a cabal-version field based on the features used by the
package. This field is required because it may change how Cabal parses the
package description.

Include cabal-version field inferred by hpack

---

src/Cabal2nix.hs
src/Distribution/Nixpkgs/Haskell/Derivation.hs
src/Distribution/Nixpkgs/Haskell/FromCabal.hs

cabal2nix already provides flags for haddocks generation and enabling
tests so it makes sense to allow enabling package benchmarks as well.
Fixes #396

add benchmark enabling flag

---

src/Distribution/Nixpkgs/Fetch.hs

Nix paths allow only limited set of characters thus for example paths with "@" of paths with non-latin characters give derivation with Nix fails to parse. Quoting resolves this problem.

Put file src attribute in quotes to allow more paths

---

src/Cabal2nix.hs
src/Distribution/Nixpkgs/Haskell/PackageSourceSpec.hs

Fixes the problem described in #360 
One possible scenario when the default option for local path won't be good: get package sources with `cabal unpack autoexporter` and use `cabal2nix` on those and you'll need `hpack` to be run as a part of build even when it's not needed.

Add option for disabling hpack completely

---

src/Distribution/Nixpkgs/Fetch.hs

Reverts NixOS/cabal2nix#402. The change did not work as intended.

Revert "Put file src attribute in quotes to allow more paths"

---

src/Distribution/Nixpkgs/Haskell/FromCabal.hs
test/golden-test-cases/haddock-library.cabal
test/golden-test-cases/haddock-library.nix.golden

Reverts NixOS/cabal2nix#405. This change breaks several builds. See https://hydra.nixos.org/build/88843163 for an example.
Cc: @shlevy

Revert "Revert "Disable Haddock phase for packages with internal libraries.""

---

src/Distribution/Nixpkgs/Haskell/FromCabal.hs

They were removed in https://github.com/NixOS/nixpkgs/pull/55735

resolveInNixpkgs: stop using GNOME aliases

---

cabal2nix.cabal

The library uses [Map.!?](https://hackage.haskell.org/package/containers-0.6.0.1/docs/Data-Map-Internal.html#v:-33--63-) which is only available since containers-0.5.9.
It failed to build on my machine because of this issue.

Add a minimal version contstraint for 'containers'.

---

src/Distribution/Nixpkgs/Haskell/FromCabal/PostProcess.hs

Split outputs can be disabled, in which case $doc is the empty string.
`outputDoc` always points to the right output variable name
(either "out" or "doc").
See also https://github.com/NixOS/nixpkgs/pull/61526.

Don't hardcode $doc

---

src/Distribution/Nixpkgs/Haskell/FromCabal/PostProcess.hs

See https://github.com/NixOS/cabal2nix/pull/416#issuecomment-494096785

xmonad: Fix missing dollar escape quotes.

---

src/Cabal2nix.hs

This fixes an issue when hpack is used
in combination with doJailbreak.
Before hpack run after jailbreak (preConfigure),
now it runs before (prePatch)
closes #421
Tested on [this commit](https://github.com/turboMaCk/nixpkgs/commit/7fc33f665dedef392e0ec67cdeb3a59faf57ac09) and I can confirm this resolves the issue.

Run hpack in prePatch phase

---

hackage2nix/README.md

This adds a link to the YouTube video recently released by @peti to the `hackage2nix` README.
https://discourse.nixos.org/t/video-tutorial-how-to-re-generate-the-haskell-package-set-for-nix/4074
This is a very informative video and it explains the process of running `hackage2nix` in great detail.
I think this would be very helpful for any user looking to run `hackage2nix`, or to understand how the `haskell-updates` branch is updated in nixpkgs.

Link to the YouTube video explaining hackage2nix.

---

src/Cabal2nix.hs

See https://github.com/haskell/cabal/pull/6301 for all the details. I'd
say it's safe to merge before the Cabal PR as the only people affected
by this bug would need to work around things anyways.
CC @kmicklas

Do the right thing for 32-bit android

---

src/Distribution/Nixpkgs/Haskell/FromCabal/PostProcess.hs

Naive concatenation of `$LD_LIBRARY_PATH` can result in an empty colon-delimited segment, which tells glibc to load libraries from the current directory.
See also NixOS/nixpkgs#76804.

Fix unsafe concatenation of $LD_LIBRARY_PATH

---

README.md
cabal2nix.cabal
hackage2nix/README.md
src/Distribution/Nixpkgs/Haskell/FromCabal.hs
stack.yaml

This is my first shot at solving #431 and making it easier for more people to contribute to `stack2nix`, `stackage2nix`, and the nixpkgs Haskell package set upgrades.
I still have to make a less customised version of `./update-nixpkgs.sh` (e.g. one that doesn't push stuff), but that is for a later PR.

Improve READMEs, reproducibility, and make contributing easier

---

src/Distribution/Nixpkgs/Haskell/FromCabal/Name.hs

see https://github.com/NixOS/nixpkgs/pull/89350
The library libtdjson is a part of tdlib.

Add tdlib to libNixName

---

src/Distribution/Nixpkgs/Haskell/FromCabal/PostProcess.hs

Since https://github.com/agda/agda/commit/378020321a223d7057cd10b59b995ebac91c7a8b, Agda's Setup.hs has contained the instructions for building the builtin modules. Thus, we do not need to do it again.
I haven't tested this yet, because building Agda requires slightly more RAM than my machine has. I can test it overnight if required, though.
/cc @abbradar

[ cleanup ] don't build Agda builtins again

---

src/Distribution/Nixpkgs/Haskell/FromCabal/PostProcess.hs

Use "$out/share/bash-completion/completions" because it gets
automatically loaded by the bash-completions package if "$out/share" is
listed in the XDG_DATA_DIRS environment variable.
This combined with https://github.com/NixOS/nixpkgs/pull/103501 will
mean that nix-shell environments can have completion available.

fix bash-completion outputs

---

doc/nixpkgs-users-guide.rst

(Seems copy pasted from the example above.)

Remove unused code

---

hackage2nix/README.md

Seems like this README was not updated when stack was removed from this
repository and the old style cabal workflow was dropped in favor of
cabal v2-*. Now we need to build cabal2nix using cabal v2-build in order
for the cabal v2-run in update-nixpkgs.sh to work.

Update hackage2nix instructions to reflect cabal v2 usage

---

src/Distribution/Nixpkgs/Haskell/FromCabal/License.hs
test/golden-test-cases/BioHMM.nix.golden
test/golden-test-cases/bbdb.nix.golden
test/golden-test-cases/blosum.nix.golden
test/golden-test-cases/brittany.nix.golden
test/golden-test-cases/clumpiness.nix.golden
test/golden-test-cases/drawille.nix.golden
test/golden-test-cases/funcmp.nix.golden
test/golden-test-cases/gsasl.nix.golden
test/golden-test-cases/mnist-idx.nix.golden
test/golden-test-cases/network-protocol-xmpp.nix.golden
test/golden-test-cases/once.nix.golden
test/golden-test-cases/openexr-write.nix.golden
test/golden-test-cases/tree-fun.nix.golden

In nixpkgs, the licenses.{gpl3,gpl2,lgpl21,…} attributes are slowly
being deprecated in favor of the licenses.{gpl3Only, gpl2Only, …}
attributes which avoids confusion with the licenses.{gpl3Plus, gpl2Plus, …}
attributes. We should probably do the same as we are already doing with
the SPDX license identifiers.

feat(FromCabal.License): don't generate unclear attributes for gpl licenses

---

doc/nixpkgs-users-guide.rst

Noticed that the manual started from `7.10`.
And stated that the Nixpkgs default GHC is `8.8`.
Also `ghcjs`  is no longer in that list.

Doc: nixpkgs-users-guide: update to GHC versions

---

src/Distribution/Nixpkgs/Haskell/FromCabal/Name.hs

lzma is only an alias to xz in nixpkgs nowadays which leads to all kinds
of evaluation troubles (since such aliases are stripped and not present
if aliases are disabled).
To fix this, we preemptively respect the alias in
Distribution.Nixpkgs.Haskell.FromCabal.Name.
Reference <https://github.com/nixos/nixpkgs/issues/118996>.

FromCabal.Name: resolve library lzma to xz

---

src/Distribution/Nixpkgs/Fetch.hs
src/Distribution/Nixpkgs/Haskell/PackageSourceSpec.hs

Does what it says.
Ideally a bigger rearchitecting would have been done at the point the assumption that the kind implies the command broke down (with 854695a374862fdfe8a5881767fd17dcd39fa085), but I think that's beyond me.
Processing repositories may take longer than before if there is a big file at the same URL, since that is downloaded twice before even trying to use a version control client.
I did not add a test because I'm not sure how to do that in a way such that it can be disabled in nixpkgs (to remain in the build sandbox).
Closes #377.

fix fetching from remote archives

---

.github/workflows/haskell-ci.yml
cabal2nix.cabal

GHC 8.10.3 is not interesting for us anymore, GHC 8.10.4 is what we
currently use and GHC 8.10.5 is what we could potentially upgrade to.

ci: use GHC 8.10.4 for testing

---

src/Distribution/Nixpkgs/Haskell/PackageSourceSpec.hs

If I mistakenly pass a directory with a cabal.project file to cabal2nix-unwrapped I will get the following error message:
```
cabal2nix: nix-prefetch-url: createProcess: runInteractiveProcess: exec: does not exist (No such file or directory)
```
This pull request makes cabal2nix report a more useful error message. Currently the `fetchLocal` fetcher in `Distribution.Nixpkgs.Fetch` fails after a check by `Distribution.Nixpkgs.Haskell.PackageSourceSpec.onlyCabalFromDirectory` but the error reporting in that function uses `fail`. In the case of `MaybeT IO a` this means that the result is `Nothing`, the `msum` in `fetch` tries the next fetcher, `nix-prefetch-url` will fail instead and the original failure will be silently dropped.
The commit modifies `onlyCabalFromDirectory` to apply `fail` in …

Improve error message when the source URI is a directory that doesn't contain a .cabal file

---

src/Distribution/Nixpkgs/Haskell/FromCabal/PostProcess.hs

It is no longer used since 2015, see:
* https://github.com/ucsd-progsys/liquid-fixpoint/commit/a6bfa04a1d922941fbba860f9f55c4f2ae18f9b6
* https://github.com/ucsd-progsys/liquid-fixpoint/commit/412c3e95c0f606b58a52cd8a69c62ba9b4902668

liquid-fixpoint: Remove ocaml dependency

---

cabal2nix.cabal
hackage2nix/Main.hs

Depends on <https://github.com/peti/distribution-nixpkgs/pull/10>
If you're interested, below is a diff of running `hackage2nix` on current `haskell-updates`. Minus the noise, you can see that it actually manages to resolve some new things correctly it couldn't before which is good to see.
Only downside of this currently is that the `nixpkgs` argument must be a valid nix path, I think I'll add a format check to it, so users at least know what's going on.
<details>
```diff
diff --git a/pkgs/development/haskell-modules/hackage-packages.nix b/pkgs/development/haskell-modules/hackage-packages.nix
index 6a82b343bf9..3632dc767b7 100644
--- a/pkgs/development/haskell-modules/hackage-packages.nix
+++ b/pkgs/development/haskell-modules/hackage-packages.nix
@@ -12982,7 +12982,7 @@ self: {
license = …
```

hackage2nix: adjust to distribution-nixpkgs 1.6.0

---

src/Distribution/Nixpkgs/Haskell/PackageSourceSpec.hs

Closes #507 
This PR makes `hpack` force generation of a `cabal` file. `hpack` will bail out early if the version of `hpack` used to generate an existing `cabal` file is newer than itself. This results in a package that can't be built.

Don't use hpack when cabal file is in the directory

---

src/Distribution/Nixpkgs/Haskell/FromCabal/License.hs
test/golden-test-cases/ede.nix.golden
test/golden-test-cases/gogol-adexchange-buyer.nix.golden
test/golden-test-cases/gogol-admin-emailmigration.nix.golden
test/golden-test-cases/gogol-affiliates.nix.golden
test/golden-test-cases/gogol-apps-tasks.nix.golden
test/golden-test-cases/gogol-appstate.nix.golden
test/golden-test-cases/gogol-blogger.nix.golden
test/golden-test-cases/gogol-datastore.nix.golden
test/golden-test-cases/gogol-dfareporting.nix.golden
test/golden-test-cases/gogol-firebase-rules.nix.golden
test/golden-test-cases/gogol-gmail.nix.golden
test/golden-test-cases/gogol-kgsearch.nix.golden
test/golden-test-cases/gogol-maps-engine.nix.golden
test/golden-test-cases/gogol-plus.nix.golden
test/golden-test-cases/gogol-resourceviews.nix.golden
test/golden-test-cases/gogol-translate.nix.golden
test/golden-test-cases/gogol-webmaster-tools.nix.golden
test/golden-test-cases/gogol-youtube.nix.golden
test/golden-test-cases/hxt-expat.nix.golden
test/golden-test-cases/hxt-tagsoup.nix.golden
test/golden-test-cases/openpgp-asciiarmor.nix.golden
test/golden-test-cases/swagger.nix.golden

We are currently very inconsequent in regard to "unknown" licenses. In
general they stem from packages having their license field set to
"LicenseRef-OtherLicense" accompanied by a LICENSE file which specifies
the real license.
Currently in nixpkgs "unknown" licenses result in hydra builds being
disabled for that package, but the package is not treated as "unfree" by
anything else in nixpkgs. Users don‘t get warnings when they use them
and we actually very often build those packages on hydra because they
are dependencies on other packages with free licenses.
This change simply acknowledges the fact that we are already building
and distributing most of these packages by giving them their own hydra
job.
Here are the arguments in favor of this:
* We have been distributing those packages all …

cabal2nix: Assume "unknown" hackage license to be free

---

src/Cabal2nix.hs
src/Distribution/Nixpkgs/Fetch.hs
src/Distribution/Nixpkgs/Haskell/Derivation.hs
src/Distribution/Nixpkgs/Haskell/PackageSourceSpec.hs
test/Main.hs

These are a few code refactors, 
* use `ApplicativeDo` where possible
* use explicity record syntax instead of ordering-dependent constructors
* reduce complexity of `fetchWith` by moving most arguments into a single enum in multiple steps

Refactors (ApplicativeDo, record syntax, fetchWith)

---

README.md

other code blocks use the `console` formatted blocks, this change makes that formatting consistent across other code blocks.
[rendered version](https://github.com/NixOS/cabal2nix/blob/8471aa5ab846a4ee8109c8bc284bedc0570444ed/README.md) compared to [current](https://github.com/NixOS/cabal2nix/blob/master/README.md)

doc: update `README.md` code block syntax highlighting

---

cabal2nix.cabal
hackage2nix/Main.hs
src/Cabal2nix.hs
src/Distribution/Nixpkgs/Haskell/OrphanInstances.hs
src/Distribution/Nixpkgs/Haskell/Platform.hs

In the cabal2nix project there are two flags that accept some kind of
string that needs to be converted to a `Platform` which is used for
evaluating a `.cabal` file:
* cabal2nix: `--system` accepts `cpu-vendor-os` and `cpu-os`
* hackage2nix: `--platform` only accepts `cpu-os`.
Their names should be swapped, ironically compared to what they do which
should be tackled eventually.
Initially I thought the parsing of these could be replaced by
distribution-nixpkgs new capabilities, but ran into the following issue:
distribution-nixpkgs needs to be lossless, since `Platform`s need to be
rendered again.
This is problematic when evaluating Cabal files, however: Cabal has no
notion of powerpc64le and powerpc64 and GHC's conversion logic causes
them to be both interpreted as PPC64. Package authors …

Distribution.Nixpkgs.Haskell.Platform: unify CLI platform parsing

---

src/Distribution/Nixpkgs/Haskell/FromCabal.hs
test/golden-test-cases/cheapskate.nix.golden
test/golden-test-cases/cpu.nix.golden
test/golden-test-cases/giphy-api.nix.golden
test/golden-test-cases/highlighting-kate.nix.golden
test/golden-test-cases/hit.nix.golden
test/golden-test-cases/hsyslog.nix.golden
test/golden-test-cases/pandoc.cabal
test/golden-test-cases/pandoc.nix.golden
test/golden-test-cases/pathtype.nix.golden
test/golden-test-cases/soxlib.nix.golden
test/golden-test-cases/terminal-progress-bar.nix.golden
test/golden-test-cases/texmath.nix.golden

Naturally only a buildable executable can be the mainProgram. Checking
this property eliminates some false positive mainPrograms and also gets
rid of some cases where it wasn't recognized properly. pandoc still
eludes cabal2nix, probably something strange going on with flag
resolution.

Distribution.Nixpkgs.Haskell.FromCabal: mainProgram check buildable

---

hackage2nix/Main.hs

Distribution.Nixpkgs.Haskell.FromCabal.PostProcess defines logic that in
some cases prescribes a list of platforms. Currently this gets discarded
in hackage2nix which is a bug introduced in #506.
Before said PR, hackage2nix used a fairly elaborate logic involving Set
subtraction which was necessary because the default value would be
allKnownPlatforms. Instead of that we can now use a very simple logic:
We use whatever is set or not set by PostProcess / cabal2nix in general
and then allow whatever is yielded by that to be overwritten by the
configuration passed to hackage2nix.

hackage2nix: don't discard platforms meta attr from postprocessing

---

src/Distribution/Nixpkgs/Haskell/FromCabal/Name.hs

This should fix the build of (at least) the [`flac`](https://hackage.haskell.org/package/flac) hackage package.
closes https://github.com/NixOS/cabal2nix/issues/566

Add FLAC -> flac system library mapping

---

distribution-nixpkgs/CHANGELOG.md
distribution-nixpkgs/distribution-nixpkgs.cabal

This release is mostly for the benefit of `haskell.packages.ghc942`, since we currently need to disable the test suite there.

distribution-nixpkgs: prepare 1.7.0.1 release

---

cabal2nix/src/Distribution/Nixpkgs/Haskell/FromCabal/PostProcess.hs

This prevent potential breakage when upstream outputs splitting.
Required by NixOS/nixpkgs#209128

Use lib.get{Lib,Dev} to correctly locate outputs

---

hackage-db/CHANGELOG.md
hackage-db/hackage-db.cabal
hackage-db/src/Distribution/Hackage/DB/Path.hs

From 3.10.1.0 onwards, cabal-install uses XDG directories to store its state and cache components.  cabal2nix expects to find the Hackage tarball in ~/.cabal, where it may no longer be located.
This commit changes cabal2nix to look in ~/.cabal if that directory exists (which matches the behaviour of cabal-install itself), but otherwise looks in the appropriate XDG directory.

hackage-db: support cabal-install 3.10.1.0 XDG paths.

---

cabal2nix/src/Distribution/Nixpkgs/Haskell/FromCabal/PostProcess.hs

See https://github.com/NixOS/nixpkgs/pull/240235.
This produces the derivation we want:
```diff
diff --git a/pkgs/development/haskell-modules/hackage-packages.nix b/pkgs/development/haskell-modules/hackage-packages.nix
index e5b3ee11495..4cc3ecfed70 100644
--- a/pkgs/development/haskell-modules/hackage-packages.nix
+++ b/pkgs/development/haskell-modules/hackage-packages.nix
@@ -250244,8 +250244,9 @@ self: {
}) {};
"rest-rewrite" = callPackage
-    ({ mkDerivation, base, containers, hashable, monad-loops, mtl
-     , parsec, process, QuickCheck, text, time, unordered-containers
+    ({ mkDerivation, base, containers, graphviz, hashable, monad-loops
+     , mtl, parsec, process, QuickCheck, text, time
+     , unordered-containers, z3
}:
mkDerivation {
pname = "rest-rewrite";
@@ -250259,10 …
```

cabal2nix: Add graphviz and z3 to rest-rewrite test deps

---

cabal2nix/src/Distribution/Nixpkgs/Haskell/FromCabal/PostProcess.hs

This PR changes the cabal2nix hooks for the `tz` Haskell package.  Originally, the `tz` package had a hook that added a phase override for `preConfigure` that looked like the following:
```nix
preConfigure = "export TZDIR=${pkgs.tzdata}/share/zoneinfo";
```
This works for `hackage2nix`, but the problem is that when using `cabal2nix` by itself, this produces a Nix file like the following:
```nix
{ mkDerivation, base, binary, bytestring, containers, criterion
, data-default, deepseq, HUnit, lens, lib, QuickCheck, tasty
, tasty-hunit, tasty-quickcheck, tasty-th, template-haskell, thyme
, time, timezone-olson, timezone-series, tzdata, vector
}:
mkDerivation {
pname = "tz";
version = "0.1.3.6";
preConfigure = "export TZDIR=${pkgs.tzdata}/share/zoneinfo";
...
}
```
This is trying to reference …

Setup tz package overrides to reference system tzdata package correctly

---

cabal2nix/CHANGELOG.md
cabal2nix/hackage2nix/Main.hs

Since my system is currently missing the locale `C.UTF-8` which we set in `regenerate-hackage-packages.nix` I want to make `hackage2nix` locale independent. The impurity is driving me nuts. Since we all edit the same file with hackage2nix hardcoding the locale makes total sense.
From memory I think the locale can affect two things:
1. It affects the encoding with which hackage-packages.nix get’s written.
2. It affects the ordering of entries in hackage-packages.nix
After reading the documentation for `base:System.IO` I am moderately certain that this change fixes 1.
Regarding 2 I am just confused. From reading the code I think the ordering depends on the Ord instances of PackageName and Version. Those are newtypes which in the end all boil down to the Ord instances of ShortByteString or …

Make hackage2nix locale independent

---

cabal2nix/src/Distribution/Nixpkgs/Haskell/FromCabal/Flags.hs
cabal2nix/src/Distribution/Nixpkgs/Haskell/FromCabal/PostProcess.hs

After this is merged, I'll open a corresponding PR for nixpkgs that updates `cabal2nix-unstable` and adjusts the overrides accordingly.

FromCabal.PostProcess: remove gitAnnexHook 

---

cabal2nix/src/Distribution/Nixpkgs/Haskell/FromCabal/PostProcess.hs

- haddock-test is uploaded to hackage now
- The `doCheck = false;` can live in nixpkgs as can the `unset GHC_PACKAGE_PATH` should it be needed again (it isn't executed currently).

FromCabal.PostProcess: drop haddockHook

---

cabal2nix/cabal2nix.cabal
distribution-nixpkgs/CHANGELOG.md
distribution-nixpkgs/distribution-nixpkgs.cabal
hackage-db/hackage-db.cabal
language-nix/language-nix.cabal

Otherwise test suite won't succeed with 9.10.1.

distribution-nixpkgs: prepare release 1.7.1.1 

---

cabal2nix/cabal2nix.cabal
cabal2nix/src/Distribution/Nixpkgs/Haskell/Derivation.hs
cabal2nix/src/Distribution/Nixpkgs/Haskell/FromCabal.hs

See https://github.com/nixOS/nixpkgs/commit/a62b24be6d650757deb8fe222763f436a53650ff

Distribution.Nixpkgs.Haskell.Derivation: remove obsolete enableSplitObjs

---

cabal2nix/src/Distribution/Nixpkgs/Haskell/FromCabal/Configuration.hs

This fixes compilation of cabal2nix with text >= 2.1.2.
Resolves #639.

cabal2nix: fix missing qualified on a Data.Text import

---

cabal2nix/src/Distribution/Nixpkgs/Haskell/Derivation.hs
cabal2nix/src/Distribution/Nixpkgs/Haskell/FromCabal.hs
cabal2nix/src/Distribution/Nixpkgs/Haskell/FromCabal/PostProcess.hs
cabal2nix/test/golden-test-cases/hoogle.nix.golden

We refactor testTarget from an unstructured string, to a list of strings representing testTargets.
See the corresponding nixpkgs PR: https://github.com/NixOS/nixpkgs/pull/306283/files

Change testTarget -> testTargets

---

doc/frequently-asked-questions.rst
doc/nixpkgs-users-guide.rst

`haskell.lib` is used in cabal2nix itself, but since those functions
aren't being deprecated yet it would be a bit breakful to replace that
right now.

Documentation changes to cope with haskell.lib.compose

---

cabal2nix/cabal2nix.cabal
cabal2nix/src/Cabal2nix.hs
cabal2nix/src/Distribution/Nixpkgs/Color.hs
cabal2nix/src/Distribution/Nixpkgs/Fetch.hs
cabal2nix/src/Distribution/Nixpkgs/Haskell/PackageSourceSpec.hs

This adds terminal colors to `cabal2nix`'s output. This checks if `stderr` `isatty` so that output will not be colored if (for example) `cabal2nix`'s `stderr` is being piped to a file. It also respects the `$NO_COLOR` and `$FORCE_COLOR` environment variables for toggling the output coloring (see [no-color.org](https://no-color.org/)).
A couple small changes while I was preparing this:
1. I added `nix-prefetch-scripts` to the `shell.nix` so that you can run `cabal2nix` successfully while hacking on it.
2. I added a line to print the fetcher command (like `nix-prefetch-git ...`) before we run it. This makes it a lot clearer where the errors come from, and which errors are being ignored (because we're trying another fetcher).
Example output:

Terminal colors for output

---

.github/workflows/haskell-ci.yml
cabal2nix/cabal2nix.cabal
distribution-nixpkgs/distribution-nixpkgs.cabal
hackage-db/hackage-db.cabal
language-nix/language-nix.cabal

The ubuntu-20.04 runners have been deprecated and disabled.
Side note: A bit annoying, that `haskell-ci` is so outdated on hackage and thus in nixpkgs. The dev shell for cabal2nix provides it, but it's way too old, so I had to build it from source. Tried updating it in nixpkgs to an unstable version, but didn't succeed, yet.

.github: run on ubuntu-24.04

---

.gitignore
cabal2nix/src/Distribution/Nixpkgs/Haskell/FromCabal/PostProcess.hs

See https://github.com/NixOS/nixpkgs/pull/400565 / https://github.com/NixOS/nixpkgs/pull/398707 for rationale.

FromCabal.PostProcess: remove apple_sdk frameworks for hfsevents

---

cabal2nix/src/Distribution/Nixpkgs/Haskell/FromCabal/Flags.hs
cabal2nix/src/Distribution/Nixpkgs/Haskell/FromCabal/PostProcess.hs

The package is broken and has a dependency on nettools, which I want to
rename in https://github.com/NixOS/nixpkgs/pull/416056

Remove broken liquid-fixpoint
