NixOS/cabal2nix

- src/hackage2nix.hs
This package is seem to be stable now
> Remove xmonad-screenshot from broken packages

- hackage2nix/src/Main.hs
> Replace fromMaybe&Map.lookup with Map.findWithDefault

- src/Distribution/Nixpkgs/Haskell/FromCabal/PostProcess.hs
I tried to port the manual changes I did in my local `configuration-common.nix` to have various `gi-*` packages work. There may be mistakes/typos as I haven't had the opportunity to build it, let alone run it.
> Fix build environment for gi-* packages

- src/Distribution/Nixpkgs/Haskell/Derivation.hs
- src/Distribution/Nixpkgs/Haskell/FromCabal.hs
- src/Distribution/Nixpkgs/Haskell/FromCabal/Normalize.hs
I'll open a PR for nixpkgs soon too
> Put benchmark dependencies in benchDepends

- src/Distribution/Nixpkgs/Haskell/Derivation.hs
- src/Distribution/Nixpkgs/Haskell/FromCabal.hs
- src/Distribution/Nixpkgs/Haskell/FromCabal/Normalize.hs
Note that this changes the generated nix expression.
> Use benchmark instead of bench

- src/Distribution/Nixpkgs/Haskell/FromCabal/PostProcess.hs
Ref: NixOS/nixpkgs#8a62a9b064ed52da5ab2fd9520cdd218ce4445cb
> Apply nixpkgs rename: webkitgtk24x -> webkitgtk24x-gtk3

- src/Cabal2nix.hs
cc @peti , am working on generating nix builds from `GHCJS` stack files. This requires getting out the raw derivation information to construct a `hackage-packages.nix`-like file. 
This PR exposes `cabal2nix'`, which gives access to the underlying derivation, alleviating us from having to call `cabal2nix` as a subprocess, and also giving flexibility in regards to command line arguments (e.g. `--compiler ghcjs`).
> Expose derivation info from cabal2nix'

- src/Distribution/Nixpkgs/Haskell/PackageSourceSpec.hs
As a bonus, save a traversal over every package version in the common
case of no specified package version (`toDescList` vs `reverse .
toAscList`).
Fixes #287.
> Don't ignore user-specified package version on fetch

- src/Distribution/Nixpkgs/Haskell/PackageSourceSpec.hs
While running into issue #333 myself (Unicode characters in cabal2nix's cabal file itself!) I had a hard time discovering that this was the issue since cabal parse errors are displayed nowhere.
> Display cabal file parsing errors to user

- src/Cabal2nix.hs
This replicates GHC's normalization logic so that Cabal's built in parsers can
be used. This should ensure maximum compatibility with how the Cabal file will
actually be evaluated during the build.
Additionally, this adds support for passing in the full LLVM style platform
triple/quadruple (e.g. x86_64-unknown-linux-gnu) instead of just the short Nix
style (x86_64-linux). This will make it possible for the ABI to treated as part
of the OS where applicable (e.g. linux-android). We can then change
`make-package-set.nix` to use `hostPlatform.config` instead of
`hostPlatform.system` to get the full information.
> Support all architectures and OSs that GHC and Cabal support

- src/Distribution/Nixpkgs/Haskell/PackageSourceSpec.hs
This is because in a nomal workflow, you would generate the .cabal
every now and then from the package.yaml file.
If you forget to do this generation and you have an old .cabal file
in your tree (common because for users of hpack, .cabal files are
usually in .gitignore), then until now nix would pick up the outdated
cabal file and you would accidentally be running against outdated cabal
contents.
So in this commit we change the logic from
"if *.cabal doens't exist, check if package.yaml exist, if so use hpack"
to
"if package.ymal exists, use hpack, otherwise use *.cabal"
> If both package.yaml and cabal exist, prefer package.yaml.

- src/Distribution/Nixpkgs/Haskell/FromCabal/Flags.hs
See NixOS/nixpkgs#67464 for original discussion
> Enable inlineMarkdown on pandoc-placetable

- src/Distribution/Nixpkgs/Haskell/FromCabal/License.hs
https://github.com/NixOS/nixpkgs/pull/82564
> FromCabal.License: drop jasper

- src/Distribution/Nixpkgs/Haskell/FromCabal/Name.hs
Following @cdepillabout instructions from https://github.com/NixOS/nixpkgs/pull/105298#discussion_r532132788.
> Map ff to libff

- src/Distribution/Nixpkgs/Haskell/OrphanInstances.hs
Part of a fix for https://github.com/NixOS/nixpkgs/issues/116095
See also https://github.com/peti/distribution-nixpkgs/pull/8
> Add support for the aarch64-linux platform

- hackage2nix/Main.hs
- src/Distribution/Nixpkgs/Haskell/FromCabal/Configuration.hs
This commit is preparing the switch to multiple config files in nixpkgs.
I will soon create a PR to nixpkgs demonstrating the usage of multiple config files.
> hackage2nix: Accept multiple config files

- doc/frequently-asked-questions.rst
It's complicated and requires various incantations, and isn't documented anywhere currently that I could find.
I'm not sure what the difference between the user's guide and FAQ is, but I went with the FAQ.
> doc: Explain how to use GHC with LLVM

- doc/nixpkgs-users-guide.rst
See https://github.com/haskell/haskell-language-server/issues/493. This seems to be the recommended way to setup the language server for multiple GHCs / projects.
> doc: mention using Lorri with haskell-language-server

- README.md
This is basically what I've used so far and works quite well without
being too opinionated and using mostly vanilla cabal.
Also gets rid of the outdated suggestion to use stack which isn't
possible anymore.
I'm not sure this is the ideal way we should settle on, but it is a
quite comfortable solution that doesn't require any changes at this
point.
[Rendered](https://github.com/NixOS/cabal2nix/blob/doc/development-environment/README.md#building)
> README: suggest shared development env for cabal2nix related packages

- doc/frequently-asked-questions.rst
> doc/faq: reflect upstream changes in ghcWithPackages with LLVM section

- src/Distribution/Nixpkgs/Haskell/FromCabal/Flags.hs
See https://github.com/jgm/pandoc/commit/d414b2543a1686007e84c54bc711dff969dfb569.
> Flags: remove unnecessary "https" flag from Pandoc

- doc/nixpkgs-users-guide.rst
as noted in the instructions, this is the easiest thing, and what
beginners will probably do first.
> move instructions for nix-shell to top of section
